FROM maven:3.8.3-openjdk-17-slim AS builder
WORKDIR /app
COPY . .
RUN mvn clean package
FROM openjdk:17-jdk-alpine
COPY --from=builder /app/target/ms-cuenta-movimientos-devsu-0.0.1-SNAPSHOT.jar /app/ms-cuenta-movimientos.jar
ENTRYPOINT ["java", "-jar", "/app/ms-cuenta-movimientos.jar"]